### ISSUE TITLE
MultiIndex insert does not work because pandas hasnans does not support MultiIndex 

### ISSUE THREAD

**Issue by legendawes** [notsambeck/pandabase#3]
https://github.com/notsambeck/pandabase/blob/435b20f9087a0fc1fc62b0a2661f0efdae14820b/pandabase/pandabase.py#L91

Usage: pandabase.to_sql(table_df, table_name='table_name', con=engine, how='create_only')

Raises pandas error: NotImplementedError: isna is not defined for MultiIndex
pd.__version__: 0.25.3

**Comment by legendawes** [comment]
Created pull request https://github.com/notsambeck/pandabase/pull/4 with the following workaround:
if not isinstance(df.index, pd.MultiIndex) and df.index.hasnans:
    raise ValueError('DataFrame index has NaN values.')

**Comment by notsambeck** [comment]
Thanks for noting this issue. Supporting multi-indexes would be a project - doable if someone wanted to work on it, but not something that I have time to jump into right away.

Can you get around this cleanly with some kind of clever re-indexing? I'm not easily imagining a scenario where a multi-index is much nicer than mapping your multiple indices into a single index. If that's not true, I would be interested to hear about your use case.

**Comment by notsambeck** [comment]
I’m going to close this as outside the scope of pandabase. Feel free to reopen if you are still thinking about this issue though.
