### ISSUE TITLE
Bulk insert documentation

### ISSUE THREAD

**Issue by mazzma12** [notsambeck/pandabase#5]
Hi,
This library looks to fill a gap I was looking for. However, does this support bulk insert? I could not find mention of this in the documentation.
In vanilla pandas it is referred to by the `method='multi'` kwarg in the `to_sql` method: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_sql.html#pandas.DataFrame.to_sql
Thank you!

**Comment by notsambeck** [comment]
Hey, good question.

pandabase handles inserting multiple rows, no problem. When appending, it does use the SQLAlchemy insert_many functionality. When upserting, currently it handles rows one-by-one.

I have been talking with @ThibTrip  about [pangres](https://github.com/ThibTrip/pangres), which currently only handles Postgres. Pangres is quite a bit faster than pandabase for multiple upserts. See [relative performance graphs](https://github.com/notsambeck/pandabase_profile) here.

I would like to bring pangres performance to pandabase, or vice versa - mostly waiting to hear how the pandas to_sql_upsert PR is resolved, as that would make this project mostly irrelevant.

**Comment by mazzma12** [comment]
Thanks for the answer, indeed without the insert_many, it may turn out to be really slow for decent size datasets.

**Comment by notsambeck** [comment]
It's slower than it could be, on the order of 2x. Check out Pangres, I hear it's in a good place right now.
