### ISSUE TITLE
Support specifying the datatype for columns ( equivalent to dtype in pandas to_sql)

### ISSUE THREAD

**Issue by Hungsiro506** [notsambeck/pandabase#6]
Is there any equivalent to **dtype** in panas to_sql() ?. 
I read through the codebase and i think the answer is No.!!

**Comment by notsambeck** [comment]
You are correct, there is currently no way to set a non-default datatype - everything is mapped to the basic datatypes defined in [helpers.py](https://github.com/notsambeck/pandabase/blob/master/pandabase/helpers.py). Do you have a need to write a different datatype in your database? Is it something additional/unsupported, or are you trying to coerce from one Pandas type to a different SQL type? 

I did address your earlier comments about lack of documentation for the schema kwarg in the readme, thanks for noting that.

**Comment by notsambeck** [comment]
Closing this; please reopen if you want to discuss.

**Comment by cweber9843** [comment]
I ran into this problem when I wanted to use pandabase to upsert as postgres database with postgis. The geometry data type will not be translated, when using pandabase on a geopandas dataframe. 

The result is a `ProgrammingError: (psycopg2.ProgrammingError) can't adapt type 'LineString'`

Do you have any further plans to implement dtypes?
