### ISSUE TITLE
question regarding usage

### ISSUE THREAD

**Issue by sanzgiri** [notsambeck/pandabase#8]
Hi, I have a couple of question regarding the "upsert" functionality

- Do I have to use pandabase to create the table using "create_only" or can I do an "upsert" into an existing table? 
- Doing an upsert into an existing table is not working for me. I am loading a dataframe that has the index set to the primary_key in the table. Is this the correct way?

Thanks,
Ashutosh

**Comment by notsambeck** [comment]
Good questions:
1. Yes, you can upsert to a new table; upsert works exactly like insert (including creating new tables) unless data already exists with the same PK.
2. You can use pandabase to work with existing SQL tables just fine, there's nothing special about the tables created with pandabase vs. raw SQL vs. other tools. 

**HOWEVER** - I have a few guesses about why it's not working for you.

pandabase opaquely renames column and table names to a very limited range of characters: lowercase letters, numbers, and _. If your DataFrame has column names that include additional characters, they will be converted into that format (e.g. "ColumnName(2+2)" gets converted to "columnname_2_2_" by function pandabase.helpers.clean_name). This subset of legal characters is probably stricter than necessary, but they are known to work fine.

Additionally, if there is a datatype mismatch between the existing database PK column and DataFrame.index, you should get an error explaining the mismatch.

It would be relatively easy to remove the call to clean_name, or make clean_names=True a parameter in pandabase.to_sql, if that would solve your problem.

**Comment by sanzgiri** [comment]
Thanks, I think the dataframe I was trying to load did not have its index set to the primary key. That was causing the original problem. There are a couple of issues I am running into.

- I have a timestamp column in my database and when I try to upsert a dataframe with a column that has a datetime64[ns] field, I get this error: `AttributeError: 'Timestamp' object has no attribute 'translate'` Do I need to handle timestamps differently?

- The performance is pretty slow. It took me ~ 4min to do an upsert of a dataframe with ~1000 rows and 10 columns. Any tips to improve performance?

Thanks for your help!

**Comment by notsambeck** [comment]
I haven't seen the first issue before... can you please include the full error/trace, and ideally code to reproduce it? I believe that's coming from a lower-level library. Is the timestamp already in UTC?

Regarding performance - pandabase is not super fast, but it should be much, much faster than that. Can you please post the code that results in that performance? My testing shows 1000 rows x 10 columns taking less than one second. see https://github.com/notsambeck/pandabase_profile/blob/master/pandabase_vs_pangres.ipynb for a usage example and benchmarks

**Comment by notsambeck** [comment]
Googling this error, it looks like it's related to MySQL, which pandabase doesn't support currently. I would recommend checking out https://github.com/ThibTrip/pangres

**Comment by sanzgiri** [comment]
Thanks, appreciate the pointer to pangres. Will try it out!
